import type { SettingDef, SettingGroupDef, SettingType } from "@/lib/settings/types";

/**
 * TÜM ayarların tek kaynağı (T9).
 *
 * Ayarlar ekranı bu şemadan otomatik üretilir: tip → widget eşlemesi,
 * doğrulama, audit ve "varsayılana dön" bedava gelir. Yeni ayar eklemek
 * buraya bir satır yazmaktır.
 *
 * GELİŞTİRME İLKESİ (PLAN.md İlkeler #5): eşik, aralık, limit, saklama süresi
 * ve sıklık değerleri koda sabit yazılmaz — her milestone kendi ayarlarını
 * buraya ekler.
 */

export const settingGroups: SettingGroupDef[] = [
  { key: "general", label: "Genel", description: "Dil, tema, saat dilimi" },
  {
    key: "monitoring",
    label: "İzleme & Saklama",
    description: "Metrik toplama sıklığı ve katman saklama süreleri (T1)",
  },
  {
    key: "health",
    label: "Servis İzleme",
    description:
      "Health-check varsayılanları — her monitör kendi değerini tanımlayarak bunları ezebilir",
  },
  {
    key: "alerts",
    label: "Alarm Eşikleri",
    description:
      "İzleme ekranında renk kodlaması, M1.3'ten itibaren bildirim tetikleyicisi",
  },
  {
    key: "docker",
    label: "Docker",
    description: "Container ölçümü ve restart-loop tespiti",
  },
  {
    key: "hardware",
    label: "Donanım",
    description: "Sıcaklık, S.M.A.R.T ve RAID/ZFS izleme eşikleri",
  },
  {
    key: "home",
    label: "Ana Sayfa",
    description: "Hava durumu konumu, internet göstergesi ve kiosk görünümü",
  },
  {
    key: "network",
    label: "Ağ",
    description: "Ağ taraması, cihaz envanteri ve Wake-on-LAN",
  },
  {
    key: "tailscale",
    label: "Tailscale",
    description: "Tailnet durumu, peer listesi ve düğüm anahtarı bitiş takibi",
  },
  {
    key: "proxy",
    label: "Proxy & DDNS",
    description: "Alan adı yayınlama, sertifika bitiş takibi ve dinamik DNS",
  },
  {
    key: "apps",
    label: "Uygulamalar",
    description:
      "Kart adreslerinin çözümlenmesi ve Docker etiketlerinden otomatik kart keşfi",
  },
  {
    key: "notify",
    label: "Bildirim Kanalları",
    description:
      "Her kanalın kendi seviye filtresi var — kritik olanı telefona, gerisini sadece panele düşürebilirsin",
  },
  {
    key: "updates",
    label: "Güncelleme & Yedek",
    description:
      "Panel güncelleme KURMAZ, yalnızca haber verir — ne zaman kurulacağı senin kararın",
  },
  {
    key: "files",
    label: "Dosyalar",
    description: "Dosya yöneticisinin erişebileceği kökler ve disk analizi sınırları",
  },
  {
    key: "logs",
    label: "Loglar",
    description: "Container ve journald loglarının toplanması, saklanması ve budanması",
  },
  {
    key: "security",
    label: "Güvenlik",
    description: "Oturum ömrü ve kaba kuvvet koruması",
  },
  {
    key: "api",
    label: "Dış API",
    description:
      "Bearer token ile çalışan /api/v1 yüzeyi — script, Grafana, mobil uygulama ve n8n için",
  },
  {
    key: "integration",
    label: "Dış Entegrasyon",
    description:
      "MQTT yayını ve Home Assistant keşfi — panelin verisi panelde kilitli kalmasın",
  },
  {
    key: "jobs",
    label: "Panel İşleri",
    description: "Arka plan işlerinin çalışma sıklıkları — değişiklik anında uygulanır",
  },
];

/** Bildirim seviyeleri — kanal başına en düşük seviye filtresi (M1.3). */
export const LEVEL_OPTIONS = [
  { value: "info", label: "Bilgi ve üstü" },
  { value: "warning", label: "Uyarı ve üstü" },
  { value: "critical", label: "Yalnızca kritik" },
];

type ChannelField = {
  key: string;
  label: string;
  type: SettingType;
  help?: string;
  default?: string | number | boolean;
};

/**
 * Bir bildirim kanalının ayarlarını üretir.
 *
 * Elle yazmak yerine üretilmesinin sebebi tembellik değil TUTARLILIK: her
 * kanalın mutlaka bir `enabled` ve bir `min_level` ayarı olmalı. Beş kanalı
 * elle yazmak, er ya da geç birinde `min_level`'ı unutmak demekti — ve bu,
 * "neden bu kanala bildirim düşmüyor?" diye saatlerce aranan türden bir hata.
 *
 * Anahtarlar `notify.<kanal>.<alan>` biçimindedir (ör. `notify.telegram.token`).
 */
function notifyChannel(id: string, label: string, fields: ChannelField[]): SettingDef[] {
  const fallback = (type: SettingType) =>
    type === "bool" ? false : type === "int" || type === "float" ? 0 : "";

  return [
    {
      key: `notify.${id}.enabled`,
      group: "notify",
      section: label,
      type: "bool",
      default: false,
      label: "Etkin",
    },
    ...fields.map<SettingDef>((field) => ({
      key: `notify.${id}.${field.key}`,
      group: "notify",
      section: label,
      type: field.type,
      default: field.default ?? fallback(field.type),
      label: field.label,
      help: field.help,
    })),
    {
      key: `notify.${id}.min_level`,
      group: "notify",
      section: label,
      type: "enum",
      default: "warning",
      label: "En düşük seviye",
      options: LEVEL_OPTIONS,
    },
  ];
}

export const settingDefs: SettingDef[] = [
  // ---------- Genel ----------
  {
    key: "general.language",
    group: "general",
    type: "enum",
    default: "tr",
    label: "Dil",
    options: [
      { value: "tr", label: "Türkçe" },
      { value: "en", label: "English" },
    ],
    help: "Arayüz dili. (Çeviri altyapısı henüz eklenmedi — şimdilik yalnızca kayıt.)",
  },
  {
    key: "general.theme",
    group: "general",
    type: "enum",
    default: "system",
    label: "Tema",
    options: [
      { value: "system", label: "Sistem" },
      { value: "light", label: "Açık" },
      { value: "dark", label: "Koyu" },
    ],
  },
  {
    key: "general.timezone",
    group: "general",
    type: "string",
    default: "Europe/Istanbul",
    label: "Saat dilimi",
    envVar: "TZ",
    help: "Zaman damgalarının gösteriminde kullanılır.",
  },
  {
    key: "general.ui_refresh_interval",
    group: "general",
    type: "int",
    default: 5,
    min: 2,
    max: 120,
    unit: "sn",
    label: "Arayüz yenileme aralığı",
    help: "Canlı kartların kendini ne sıklıkla tazeleyeceği.",
  },

  // ---------- İzleme & Saklama (T1) ----------
  {
    key: "monitoring.collect_interval",
    group: "monitoring",
    section: "Toplama",
    type: "int",
    default: 5,
    min: 5,
    max: 60,
    unit: "sn",
    label: "Metrik toplama aralığı",
    help: "Ham metriklerin çözünürlüğü. Büyütmek veritabanı yükünü azaltır.",
  },
  {
    key: "monitoring.retention.raw_hours",
    group: "monitoring",
    section: "Saklama süreleri",
    type: "int",
    default: 24,
    min: 1,
    max: 168,
    unit: "saat",
    label: "Ham metrik saklama",
    help: "Bu süreden eski ham örnekler budanır (rollup'lar korunur).",
  },
  {
    key: "monitoring.retention.minute_days",
    group: "monitoring",
    section: "Saklama süreleri",
    type: "int",
    default: 7,
    min: 1,
    max: 90,
    unit: "gün",
    label: "1 dakikalık metrik saklama",
  },
  {
    key: "monitoring.retention.hour_days",
    group: "monitoring",
    section: "Saklama süreleri",
    type: "int",
    default: 90,
    min: 1,
    max: 730,
    unit: "gün",
    label: "1 saatlik metrik saklama",
  },
  {
    key: "monitoring.retention.day_months",
    group: "monitoring",
    section: "Saklama süreleri",
    type: "int",
    default: 24,
    min: 1,
    max: 120,
    unit: "ay",
    label: "Günlük metrik saklama",
    help: "İzleme raporlarının kaç ay geriye gideceğini belirler.",
  },
  {
    key: "monitoring.rollup_cron",
    group: "monitoring",
    section: "Saklama süreleri",
    type: "cron",
    default: "*/5 * * * *",
    label: "Rollup/budama sıklığı",
    help: "Ham veriyi katmanlara toplayan ve eskiyi budayan işin çalışma sıklığı.",
  },
  {
    key: "monitoring.disks",
    group: "monitoring",
    section: "Toplama",
    type: "string",
    default: "",
    label: "İzlenecek disk bölümleri",
    help: "Virgülle ayrılmış bağlama noktaları (ör. /, /mnt/veri). Boş bırakılırsa gerçek dosya sistemleri kendiliğinden bulunur.",
  },
  {
    key: "monitoring.net_interfaces",
    group: "monitoring",
    section: "Toplama",
    type: "string",
    default: "",
    label: "İzlenecek ağ arayüzleri",
    help: "Virgülle ayrılmış arayüz adları (ör. enp3s0). Boş bırakılırsa yalnızca fiziksel arayüzler izlenir; docker/veth köprüleri sayılmaz.",
  },
  {
    key: "monitoring.chart_default_range",
    group: "monitoring",
    section: "Grafikler",
    type: "enum",
    default: "24h",
    label: "Grafiklerin açılış aralığı",
    options: [
      { value: "1h", label: "Son 1 saat" },
      { value: "6h", label: "Son 6 saat" },
      { value: "24h", label: "Son 24 saat" },
      { value: "7d", label: "Son 7 gün" },
      { value: "30d", label: "Son 30 gün" },
      { value: "1y", label: "Son 1 yıl" },
    ],
  },

  // ---------- Servis izleme (M1.2) ----------
  {
    key: "health.interval",
    group: "health",
    type: "int",
    default: 60,
    min: 10,
    max: 3600,
    unit: "sn",
    label: "Kontrol aralığı",
    overridable: true,
    help: "Bir monitör kendi aralığını tanımlamadıysa bu kullanılır.",
  },
  {
    key: "health.timeout",
    group: "health",
    type: "int",
    default: 10,
    min: 1,
    max: 120,
    unit: "sn",
    label: "Zaman aşımı",
    overridable: true,
  },
  {
    key: "health.retries",
    group: "health",
    type: "int",
    default: 2,
    min: 0,
    max: 10,
    label: "Tek turda yeniden deneme",
    overridable: true,
    help: "Anlık bir ağ hıçkırığı servisi düşmüş göstermesin diye aynı tur içinde tekrar denenir.",
  },
  {
    key: "health.down_threshold",
    group: "health",
    type: "int",
    default: 3,
    min: 1,
    max: 20,
    label: "Kaç ardışık başarısızlıkta 'çevrimdışı'",
    overridable: true,
    help: "Flap eden servis tek bir hatada çevrimdışı sayılmasın (M1.3'te bildirim de buna bağlı).",
  },
  {
    key: "health.uptime_retention_months",
    group: "health",
    type: "int",
    default: 12,
    min: 1,
    max: 120,
    unit: "ay",
    label: "Uptime geçmişi saklama",
  },

  // ---------- Alarm eşikleri ----------
  // İlkeler #5: eşikler koda sabit yazılmaz. M1.1'de yalnızca renk kodlamasını
  // sürerler; M1.3'te aynı değerler bildirim tetikler.
  {
    key: "alerts.cpu.warn",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 80,
    min: 1,
    max: 100,
    unit: "%",
    label: "İşlemci — uyarı eşiği",
  },
  {
    key: "alerts.cpu.crit",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 95,
    min: 1,
    max: 100,
    unit: "%",
    label: "İşlemci — kritik eşik",
  },
  {
    key: "alerts.ram.warn",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 85,
    min: 1,
    max: 100,
    unit: "%",
    label: "Bellek — uyarı eşiği",
  },
  {
    key: "alerts.ram.crit",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 95,
    min: 1,
    max: 100,
    unit: "%",
    label: "Bellek — kritik eşik",
  },
  {
    key: "alerts.disk.warn",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 80,
    min: 1,
    max: 100,
    unit: "%",
    label: "Disk — uyarı eşiği",
    overridable: true,
    help: "İleride disk bazında ezilebilecek; şimdilik tüm bölümlere uygulanır.",
  },
  {
    key: "alerts.disk.crit",
    group: "alerts",
    section: "Eşikler",
    type: "int",
    default: 90,
    min: 1,
    max: 100,
    unit: "%",
    label: "Disk — kritik eşik",
    overridable: true,
  },

  // ---------- Docker (M1.6) ----------
  {
    key: "docker.stats_interval",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 15,
    min: 5,
    max: 300,
    unit: "sn",
    label: "Container ölçüm aralığı",
    help: "Docker'ın /stats çağrısı container başına ~1 saniye sürer; çok sık ölçmek sunucuyu meşgul eder.",
  },
  {
    key: "docker.restart_loop.window",
    group: "docker",
    section: "Restart-loop tespiti",
    type: "int",
    default: 10,
    min: 1,
    max: 1440,
    unit: "dk",
    label: "Restart-loop penceresi",
    help: "Bu süre içindeki yeniden başlatmalar sayılır.",
  },
  {
    key: "docker.restart_loop.threshold",
    group: "docker",
    section: "Restart-loop tespiti",
    type: "int",
    default: 3,
    min: 2,
    max: 50,
    label: "Restart-loop eşiği",
    help: "Pencere içinde bu kadar yeniden başlatma olursa alarm üretir. Container 'up' görünse bile sinsi bir arıza olabilir.",
  },
  {
    key: "docker.stop_timeout",
    group: "docker",
    section: "Aksiyonlar",
    type: "int",
    default: 10,
    min: 1,
    max: 300,
    unit: "sn",
    label: "Durdurma bekleme süresi",
    help: "Docker önce nazikçe kapanmasını ister (SIGTERM), bu süre dolunca zorla kapatır. Veritabanı container'ları için kısa süre veri kaybına yol açabilir.",
  },
  {
    key: "docker.log_tail_lines",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 200,
    min: 10,
    max: 5000,
    unit: "satır",
    label: "Log penceresinde gösterilecek geçmiş",
  },
  {
    key: "docker.autoprune.enabled",
    group: "docker",
    section: "Otomatik disk temizliği",
    type: "bool",
    default: false,
    label: "Otomatik temizlik",
    help: "Kapalı gelir: silinen bir image'ı geri getirmek yeniden indirmek demektir. Önce elle çalıştırıp ne sildiğini görmek yeğdir.",
  },
  {
    key: "docker.autoprune.cron",
    group: "docker",
    section: "Otomatik disk temizliği",
    type: "cron",
    default: "0 5 * * 0",
    label: "Otomatik temizlik sıklığı",
  },
  {
    key: "docker.autoprune.scope",
    group: "docker",
    section: "Otomatik disk temizliği",
    type: "enum",
    default: "images-dangling",
    label: "Otomatik temizlik kapsamı",
    options: [
      { value: "images-dangling", label: "Sarkan image'lar (en güvenli)" },
      { value: "build-cache", label: "Derleme önbelleği" },
      { value: "containers", label: "Durmuş container'lar" },
      { value: "images-unused", label: "Kullanılmayan tüm image'lar" },
      { value: "volumes", label: "Bağlı olmayan volume'lar (VERİ SİLER)" },
    ],
  },
  {
    key: "updates.check_newer_tags",
    group: "docker",
    section: "Güncelleme",
    type: "bool",
    default: true,
    label: "Daha yeni sürüm etiketi ara",
    help: "Panel bugüne kadar yalnızca ETİKETİN İÇERİĞİNİN değiştiğini görebiliyordu: 'nginx:1.24' güncellenirse haber veriyor ama 'nginx:1.26' çıktığını göremiyordu. Bu açıkken kayıt defterindeki etiket listesi de okunur ve daha yeni bir sürüm varsa söylenir. Öneri tek tıkla uygulanmaz — etiketi değiştirmek compose dosyasına dokunmak demek ve o karar senindir.",
  },

  {
    key: "updates.max_bump",
    group: "docker",
    section: "Güncelleme",
    type: "enum",
    options: [
      { value: "yama", label: "Yalnızca yama (1.4.2 → 1.4.3)" },
      { value: "minor", label: "Minör sürüme kadar (→ 1.5.0)" },
      { value: "major", label: "Majör dahil her şey (→ 2.0.0)" },
    ],
    default: "minor",
    label: "Önerilecek en büyük sıçrama",
    help: "Majör sürüm çıkışları çoğunlukla kırıcı değişiklik taşır ve yükseltmeden önce sürüm notlarını okumak gerekir; varsayılan minör, bu yüzden. Majörü seçmek önerileri kapatmaz, yalnızca listeye onları da katar.",
  },

  {
    key: "updates.match_flavor",
    group: "docker",
    section: "Güncelleme",
    type: "bool",
    default: true,
    label: "Etiket çeşidini koru",
    help: "Açıkken '1.2-alpine' kullanan bir container'a yalnızca başka bir '-alpine' etiketi önerilir, düz '1.5' değil. Çeşit değiştirmek sürüm yükseltmek değil, başka bir taban imaja geçmektir — kapatırsan panel bunu bir yükseltme gibi önerir. Çok varyantlı imajlarda (php, node, postgres) gürültüyü en çok azaltan ayar budur.",
  },

  {
    key: "updates.include_prerelease",
    group: "docker",
    section: "Güncelleme",
    type: "bool",
    default: false,
    label: "Ön sürümleri de öner",
    help: "'-rc', '-beta', '-alpha' etiketleri. Kapalıyken bunlar hiç önerilmez; ama zaten bir ön sürüm kullanıyorsan (ör. 1.5.0-rc1) panel yine de bir sonraki ön sürümü ve nihai sürümü gösterir — o durumda saklamanın anlamı yok.",
  },

  {
    key: "docker.update_vuln_gate",
    group: "docker",
    section: "Güncelleme",
    type: "enum",
    options: [
      { value: "daha_kotu", label: "Yalnızca daha kötüye giderse engelle" },
      { value: "kritik", label: "Kritik açık varsa engelle" },
      { value: "kritik_yuksek", label: "Kritik ya da yüksek açık varsa engelle" },
      { value: "kapali", label: "Tara ama engelleme" },
    ],
    default: "daha_kotu",
    label: "Güncelleme öncesi güvenlik kapısı",
    help: "Panel bir container'ı güncellemeden ÖNCE yeni imajı Trivy ile tarar ve bu ölçüte göre karar verir. 'daha_kotu' (varsayılan): yalnızca yeni imaj mevcuttan DAHA FAZLA açık taşıyorsa engeller — bir iyileşmeyi asla engellemez, bir gerilemeyi asla sessizce kabul etmez. 'kritik' ve 'kritik_yuksek' daha katıdır ama ters etkisi vardır: mevcut imajda 5 kritik açık varken 3 açıklı yeni imajı da engeller ve seni daha kötü yerde tutar. 'kapali' tarar ama engellemez. Tarama sırasında etiket eski imaja geri alınır, yani engellenen bir güncelleme container'a hiç dokunmaz.",
  },

  {
    key: "docker.update_health_wait",
    group: "docker",
    section: "Image güncellemesi",
    type: "int",
    default: 30,
    min: 5,
    max: 600,
    unit: "sn",
    label: "Güncelleme sonrası doğrulama süresi",
    help: "Yeni container bu süre boyunca ayakta kalmazsa güncelleme geri alınır ve eski container geri getirilir. Yavaş açılan servisler (Home Assistant dakikalar sürebilir) için uzatılabilir.",
  },
  {
    key: "docker.exec_shell",
    group: "docker",
    section: "Terminal",
    type: "enum",
    default: "auto",
    label: "Terminal kabuğu",
    options: [
      { value: "auto", label: "Otomatik (bash varsa bash, yoksa sh)" },
      { value: "/bin/bash", label: "/bin/bash" },
      { value: "/bin/sh", label: "/bin/sh" },
      { value: "/bin/ash", label: "/bin/ash (alpine)" },
    ],
    help: "Alpine tabanlı image'larda bash yoktur; 'otomatik' bunu kendiliğinden halleder.",
  },
  {
    key: "docker.exec_idle_minutes",
    group: "docker",
    section: "Terminal",
    type: "int",
    default: 15,
    min: 1,
    max: 240,
    unit: "dk",
    label: "Terminal boşta kalma süresi",
    help: "Sekmesi kapatılmış bir terminal container içinde kabuk bırakmasın; bu süre sonunda oturum kapatılır.",
  },
  {
    key: "docker.show_stopped",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "bool",
    default: true,
    label: "Durmuş container'ları da göster",
  },

  {
    key: "docker.image_export_max_mb",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 2048,
    min: 64,
    max: 40960,
    unit: "MB",
    label: "Image dışa aktarma üst sınırı",
    help: "Dışa aktarılan tar arşivi indirilmeden önce panelin belleğine alınıyor; sınırsız bırakmak büyük bir imajda paneli belleksiz bırakır. Daha büyük imajlar için sunucuda 'docker save' kullan.",
  },

  {
    key: "docker.volume_op_timeout",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 600,
    min: 60,
    max: 7200,
    unit: "sn",
    label: "Volume kopyalama zaman aşımı",
    help: "Volume klonlama tek seferlik bir container'da 'cp -a' ile yapılıyor. Büyük volume'lerde kopyalama dakikalar sürebilir; bu süre aşılırsa işlem iptal edilir ve yarım kalan hedef volume silinir.",
  },
  {
    key: "docker.volume_export_max_mb",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 512,
    min: 16,
    max: 20480,
    unit: "MB",
    label: "Volume dışa aktarma üst sınırı",
    help: "Dışa aktarılan arşiv indirilmeden önce panelin belleğine alınıyor; sınırsız bırakmak büyük bir volume'de paneli belleksiz bırakır. Daha büyük volume'ler için yedekleme motorunu (restic) kullan. Docker boyutu hesaplayamadığı volume'lerde bu sınır uygulanmaz.",
  },

  {
    key: "docker.events_enabled",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "bool",
    default: true,
    label: "Docker olay akışını dinle",
    help: "Container'ların başlatma, durma, sonlanma ve OOM olayları Docker'dan canlı okunur ve olay kaydına yazılır. Bellek yetmediği için öldürülen (OOM) ve beklenmedik çıkış kodu ile sonlanan container'lar bildirim üretir; başlatma/durdurma gibi rutin olaylar yalnızca kaydedilir. Bir container'ın bildirim üretmesini istemiyorsan compose dosyasına 'panel.notify=false' etiketi yaz. Kapatmak akışı durdurur; olaylar bir daha görünmez.",
  },

  {
    key: "docker.events_retention_days",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "int",
    default: 30,
    min: 1,
    max: 365,
    unit: "gün",
    label: "Docker olaylarının saklama süresi",
    help: "Docker olayları alarmlardan çok daha sık yazılıyor (her başlat/durdur/yeniden başlat için bir satır), bu yüzden genel olay saklama süresinden ayrı ve daha kısa tutuluyor. Bu süreden eski Docker olayları budama işinde silinir; panelin kendi alarmları etkilenmez.",
  },

  {
    key: "docker.public_host",
    group: "docker",
    section: "Ölçüm ve görünüm",
    type: "string",
    default: "",
    label: "Container bağlantıları için sunucu adresi",
    help: "Container listesindeki yayınlanmış port rozetleri bu adrese bağlantı olur (ör. 192.168.61.114 ya da sunucu.local). Boş bırakılırsa paneli açtığın adres kullanılır — panele Tailscale üzerinden bağlanıyorsan bağlantılar da o adrese gider ve yerel ağdakinden farklı olabilir. Tek bir container için farklı bir adres gerekiyorsa compose dosyasına 'panel.url' ya da 'panel.port.<port>.url' etiketi yaz; etiket bu ayarın önüne geçer.",
  },

  // ---------- Ağ (M2.9, M2.11) ----------
  {
    key: "network.scan_enabled",
    group: "network",
    section: "Tarama",
    type: "bool",
    default: false,
    label: "Otomatik ağ taraması",
    help: "Kapalı gelir: tarama ev ağındaki her adrese bağlantı denemesi yapar ve bunu kullanıcının bilerek açması gerekir. Ekrandaki 'Şimdi tara' düğmesi bu ayardan bağımsız çalışır.",
  },
  {
    key: "network.scan_cron",
    group: "network",
    section: "Tarama",
    type: "cron",
    default: "*/30 * * * *",
    label: "Tarama sıklığı",
  },
  {
    key: "network.subnet",
    group: "network",
    section: "Tarama",
    type: "string",
    default: "",
    label: "Taranacak alt ağ",
    help: "Boş bırakılırsa sunucunun kendi yönlendirme tablosundan bulunur (ör. 192.168.61.0/24). Yalnızca /16–/30 aralığı kabul edilir.",
  },
  {
    key: "network.probe_timeout",
    group: "network",
    section: "Tarama",
    type: "int",
    default: 1,
    min: 1,
    max: 10,
    unit: "sn",
    label: "Adres başına bekleme",
  },
  {
    key: "network.scan_concurrency",
    group: "network",
    section: "Tarama",
    type: "int",
    default: 32,
    min: 1,
    max: 256,
    label: "Eşzamanlı yoklama",
    help: "Yükseltmek taramayı hızlandırır ama ev yönlendiricisinin ARP tablosunu zorlayabilir.",
  },
  {
    key: "network.oui_cron",
    group: "network",
    section: "Tarama",
    type: "cron",
    default: "0 3 1 * *",
    label: "Üretici listesi güncelleme",
    help: "IEEE'nin OUI listesi ayda bir değişiyor; MAC adreslerini üretici adına çevirmek için kullanılır. İnternet yoksa üretici alanı boş kalır, cihaz yine listelenir.",
  },
  {
    key: "speedtest.enabled",
    group: "network",
    section: "Hız testi",
    type: "bool",
    default: false,
    label: "Otomatik hız testi",
    help: "Kapalı gelir: her ölçüm onlarca megabayt indirip yüklüyor ve kotalı bağlantılarda bu bir maliyettir.",
  },
  {
    key: "speedtest.cron",
    group: "network",
    section: "Hız testi",
    type: "cron",
    default: "0 */6 * * *",
    label: "Hız testi sıklığı",
  },
  {
    key: "speedtest.endpoint",
    group: "network",
    section: "Hız testi",
    type: "string",
    default: "https://speed.cloudflare.com",
    label: "Ölçüm sunucusu",
    help: "Cloudflare'in herkese açık uçları; anahtar istemiyor ve yakın bir kenar sunucusuna düşüyor. speedtest-cli kurulmadı: imaja onlarca megabayt ve Python bağımlılığı eklerdi.",
  },
  {
    key: "speedtest.duration_seconds",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 10,
    min: 5,
    max: 30,
    unit: "sn",
    label: "Ölçüm penceresi",
    help: "Her yön için sayılan süre; öncesinde kısa bir ısınma var ve onun baytları sayılmaz. Sabit BAYT yerine sabit SÜRE ölçülüyor: hızlı bir hatta sabit bayt saniyenin onda birinde biter ve ölçülen şey hat değil gürültü olur. Pencere aşağıdaki bayt tavanı dolarsa erken biter.",
  },
  {
    key: "speedtest.max_bytes",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 500000000,
    min: 25000000,
    max: 4000000000,
    unit: "bayt",
    label: "Yön başına bayt tavanı",
    help: "Ölçüm penceresi süre dolmadan bu kadar bayt taşındıysa orada biter. Kotalı bağlantılar için maliyet freni: gigabit bir hatta yalnız süreyle sınırlı 10 saniyelik bir pencere yön başına 1 GB'ın üzerini taşır. Varsayılan 500 MB — 400 Mbit'e kadar olan hatlar tavana hiç değmez ve tam süreyi ölçer, gigabit hat ise yaklaşık 4-5 saniyelik pencere alır (eski sürümün ölçtüğü sürenin on katından fazlası).",
  },
  {
    key: "speedtest.streams",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 4,
    min: 1,
    max: 8,
    label: "Paralel akış",
    help: "Aynı anda açılan bağlantı sayısı. Tek akış hızlı bir hattı doyuramaz ve gerçek değerin çok altında sonuç verir; gerçek hız testi istemcileri de 4-8 akış açar.",
  },
  {
    key: "speedtest.download_bytes",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 5000000,
    min: 1000000,
    max: 200000000,
    unit: "bayt",
    label: "Akış başına indirme parçası",
    help: "Her akışın tek seferde istediği parça boyutu; pencere dolana kadar arka arkaya isteniyor. Toplam trafik değil — o, süre ve hıza göre belirlenir. DİKKAT: Cloudflare'in açık ucu BÜYÜK TEK İSTEKLERİ sınırlıyor — sunucuda ölçüldü, 10 MB ve üzeri istekler HTTP 429 alıp yaklaşık bir saat bloklanabiliyor, 5 MB ve altı serbest geçiyor. Küçültmek de bedava değil: aynı hatta 5 MB parça 845 Mbit ölçerken 1 MB parça istek başına düşen ek yük yüzünden yalnız 466 Mbit ölçtü.",
  },
  {
    key: "speedtest.upload_bytes",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 4000000,
    min: 1000000,
    max: 100000000,
    unit: "bayt",
    label: "Akış başına yükleme parçası",
    help: "Yalnızca TAMAMLANAN yüklemeler sayıldığı için parça, pencereye birkaç kez sığacak kadar küçük olmalı. Çok büyük seçilirse pencerede hiçbir istek bitmez ve panel tek seferlik ölçüme düşer.",
  },
  {
    key: "speedtest.retention_days",
    group: "network",
    section: "Hız testi",
    type: "int",
    default: 180,
    min: 7,
    max: 3650,
    unit: "gün",
    label: "Ölçüm saklama süresi",
  },
  {
    key: "network.alert_unknown",
    group: "network",
    section: "Tarama",
    type: "bool",
    default: true,
    label: "Yeni bilinmeyen cihazı bildir",
    help: "İlk taramada TÜM cihazlar yeni sayılır ve bildirim yağmuru olur; bu yüzden ilk tur bildirim üretmez.",
  },

  // ---------- Tailscale (M2.10) ----------
  {
    key: "tailscale.key_warn_days",
    group: "tailscale",
    type: "int",
    default: 14,
    min: 1,
    max: 180,
    unit: "gün",
    label: "Anahtar bitişine kaç gün kala uyar",
    help: "Düğüm anahtarı dolan cihaz tailnet'ten SESSİZCE düşer — sertifika bitişiyle aynı mantıkta izleniyor. Varsayılan ömür 180 gün.",
  },
  {
    key: "tailscale.check_cron",
    group: "tailscale",
    type: "cron",
    default: "45 4 * * *",
    label: "Anahtar kontrol sıklığı",
  },

  // ---------- Yayınlama & DDNS (M2.8) ----------
  {
    key: "proxy.caddy_container",
    group: "proxy",
    section: "Reverse proxy",
    type: "container",
    default: "server-panel-caddy-1",
    label: "Caddy container adı",
    help: "Yapılandırma değiştiğinde bu container'da 'caddy reload' çalıştırılır. Yeniden BAŞLATILMAZ: reload açık bağlantıları korur, restart panelin kendi oturumunu da düşürürdü.",
  },
  {
    key: "proxy.default_tls",
    group: "proxy",
    section: "Reverse proxy",
    type: "enum",
    default: "auto",
    label: "Yeni kayıtların TLS varsayılanı",
    options: [
      { value: "auto", label: "Let's Encrypt (gerçek alan adı)" },
      { value: "internal", label: "Caddy yerel CA" },
      { value: "off", label: "TLS yok (düz HTTP)" },
    ],
    help: "Yalnızca yeni kayıt formunun açılış değeri; mevcut kayıtlara dokunmaz. Yerel ağda .local adresleri yayınlıyorsan \"TLS yok\" seç: Let's Encrypt o adresler için hiçbir zaman mümkün değil, yerel CA ise her ziyarette sertifika uyarısı demek.",
  },
  {
    key: "proxy.diagnose_timeout_seconds",
    group: "proxy",
    section: "Reverse proxy",
    type: "int",
    default: 5,
    min: 2,
    max: 60,
    unit: "sn",
    label: "Yayın sınama zaman aşımı",
    help: "\"Yayını sına\" düğmesinin her adımı için üst sınır. Cevap vermeyen bir adresi süresiz beklemek, teşhisin kendisini kilitlerdi.",
  },
  {
    key: "proxy.diagnose_dns_server",
    group: "proxy",
    section: "Reverse proxy",
    type: "string",
    default: "",
    label: "Sınamada kullanılacak DNS sunucusu",
    help: "Panel container'ı genel DNS'e (1.1.1.1 gibi) bakar ve yerel adları (.local) bilmez; bu yüzden sınama, çözemediğinde yerel DNS sunucusuna doğrudan sorar. Boş bırakılırsa panele hangi IP'den erişildiyse o kullanılır — ev kurulumlarında yerel DNS genelde aynı makinededir. Pi-hole başka bir makinedeyse onun IP'sini yaz.",
  },
  {
    key: "proxy.cert_check_cron",
    group: "proxy",
    section: "Sertifika takibi",
    type: "cron",
    default: "30 4 * * *",
    label: "Sertifika kontrol sıklığı",
  },
  {
    key: "proxy.cert_warn_days",
    group: "proxy",
    section: "Sertifika takibi",
    type: "int",
    default: 21,
    min: 1,
    max: 180,
    unit: "gün",
    label: "Bitişe kaç gün kala uyar",
    help: "Let's Encrypt sertifikaları 90 günlük ve 30 gün kala yenilenir; 21 gün, yenilemenin çalışmadığını fark etmek için makul bir sınır.",
  },
  {
    key: "proxy.ddns_cron",
    group: "proxy",
    section: "DDNS",
    type: "cron",
    default: "*/15 * * * *",
    label: "DDNS kontrol sıklığı",
    help: "IP değişmediyse sağlayıcıya istek GİTMEZ; sık kontrol etmenin maliyeti yalnızca bir IP sorgusu.",
  },
  {
    key: "proxy.public_ip_url",
    group: "proxy",
    section: "DDNS",
    type: "string",
    default: "https://api.ipify.org",
    label: "Genel IP servisi",
    help: "Düz metin olarak IP döndürmeli. Ayarda tutuluyor çünkü bu servisler kapanabiliyor ve panelin yeniden derlenmesi gerekmemeli.",
  },

  // ---------- Ana sayfa (M2.7) ----------
  {
    key: "home.latitude",
    group: "home",
    section: "Hava durumu",
    type: "float",
    default: 0,
    min: -90,
    max: 90,
    label: "Enlem",
    help: "Enlem ve boylamın ikisi de 0 ise hava durumu gösterilmez. Konumunu haritadan öğrenebilirsin; Open-Meteo kullanılıyor ve API anahtarı gerekmiyor.",
  },
  {
    key: "home.longitude",
    group: "home",
    section: "Hava durumu",
    type: "float",
    default: 0,
    min: -180,
    max: 180,
    label: "Boylam",
  },
  {
    key: "home.location_label",
    group: "home",
    section: "Hava durumu",
    type: "string",
    default: "",
    label: "Konum adı",
    help: "Yalnızca ekranda gösterilir (ör. \"Kadıköy\").",
  },
  {
    key: "home.internet_check_url",
    group: "home",
    section: "İnternet göstergesi",
    type: "string",
    default: "https://1.1.1.1",
    label: "Kontrol adresi",
    help: "Ev halkı görünümündeki büyük göstergenin baktığı adres. Sunucudan bu adrese ulaşılabiliyorsa 'internet çalışıyor' denir. Dakikada bir kontrol edilir.",
  },
  {
    key: "home.kiosk_refresh",
    group: "home",
    section: "Kiosk",
    type: "int",
    default: 60,
    min: 10,
    max: 3600,
    unit: "sn",
    label: "Kiosk yenileme aralığı",
    help: "Duvara asılı ekran kendini bu aralıkla tazeler. Panelin genel yenileme aralığından ayrı: kiosk'ta veri tazeliğinden çok sessizlik önemli.",
  },

  // ---------- Uygulamalar (M2.1, M2.5) ----------
  {
    key: "apps.server_host",
    group: "apps",
    section: "Adres çözümleme",
    type: "string",
    default: "",
    label: "Sunucu adresi",
    help: "Kart adreslerindeki {host} yerine bu yazılır. Boş bırakılırsa paneli açtığın adres kullanılır — telefondan 192.168.61.114 ile giriyorsan kartlar da oraya bakar, dışarıdan bir alan adıyla giriyorsan oraya. Sabit bir adres istiyorsan buraya yaz.",
  },
  {
    key: "apps.widget_ttl",
    group: "apps",
    section: "Servis widget'ları",
    type: "int",
    default: 30,
    min: 5,
    max: 600,
    unit: "sn",
    label: "Widget verisi tazeleme aralığı",
    help: "Ekran saniyeler aralıkla yenileniyor; widget verisi bu süre boyunca önbellekten sunulur. Kısaltmak, izlenen servise panelin daha sık yük bindirmesi demek.",
  },
  {
    key: "apps.discovery_enabled",
    group: "apps",
    section: "Otomatik kart keşfi",
    type: "bool",
    default: true,
    label: "Docker etiketlerinden kart oluştur",
    help: "Yalnızca ETİKETLENMİŞ container'lar için kart açılır; hiçbir container kendiliğinden kart olmaz.",
  },
  {
    key: "apps.discovery_cron",
    group: "apps",
    section: "Otomatik kart keşfi",
    type: "cron",
    default: "*/10 * * * *",
    label: "Keşif sıklığı",
    help: "Uygulamalar ekranındaki 'Şimdi tara' düğmesiyle her an elle de çalıştırılabilir.",
  },
  {
    key: "apps.label_prefix",
    group: "apps",
    section: "Otomatik kart keşfi",
    type: "string",
    default: "panel",
    label: "Etiket öneki",
    help: "Container'a 'panel.enable=true' etiketi eklenince kart açılır. Diğer etiketler: .name .url .port .scheme .path .description .category .icon .internal_url",
  },
  /*
    Anahtar `apps.login_screen` olarak KALIYOR, adı artık sayfayı tam
    karşılamasa da. Yeniden adlandırmak, kullanıcının kapattığı listeyi
    yükseltme sırasında sessizce yeniden açardı — `appstore.*` anahtarları da
    aynı gerekçeyle bırakılmıştı. Aynı şey `apps.show_on_login` sütunu için
    de geçerli.
  */
  {
    key: "apps.login_screen",
    group: "apps",
    section: "Karşılama sayfası",
    type: "bool",
    default: true,
    label: "İşaretli kartları karşılama sayfasında göster",
    help: "Kart başına 'Karşılama sayfasında göster' seçeneği işaretlenmedikçe hiçbir kart görünmez; bu düğme tüm listeyi tek hamlede kapatmak için — işaretleri tek tek silmeden. Panel dışarıya açıksa unutma: karşılama sayfasındaki kartların adını, logosunu ve adresini oturum açmamış herkes görür.",
  },
  {
    key: "welcome.notice",
    group: "apps",
    section: "Karşılama sayfası",
    type: "richtext",
    default: "",
    label: "Duyuru",
    help: "Karşılama sayfasının üstünde şerit olarak görünür. BOŞ bırakılırsa şerit hiç çizilmez — duyurunun varsayılanı budur. Buraya yazdığın metni oturum açmamış herkes görür; sunucunun durumuyla ilgili ayrıntı değil, ev halkına söylenecek bir şey yaz (ör. 'Bu akşam 21-23 arası internet kesintisi olacak').",
  },
  {
    key: "welcome.notice_level",
    group: "apps",
    section: "Karşılama sayfası",
    type: "enum",
    default: "info",
    label: "Duyuru rengi",
    options: [
      { value: "info", label: "Bilgi (mavi)" },
      { value: "warn", label: "Uyarı (turuncu)" },
    ],
  },

  // ---------- Donanım (M1.4) ----------
  {
    key: "alerts.temp.warn",
    group: "hardware",
    section: "Sıcaklık",
    type: "int",
    default: 70,
    min: 20,
    max: 120,
    unit: "°C",
    label: "Sıcaklık — uyarı eşiği",
    help: "Sensör kendi eşiğini bildiriyorsa (çoğu işlemci bildirir) o değer önceliklidir; bu yalnızca bildirmeyenler için.",
  },
  {
    key: "alerts.temp.crit",
    group: "hardware",
    section: "Sıcaklık",
    type: "int",
    default: 85,
    min: 20,
    max: 130,
    unit: "°C",
    label: "Sıcaklık — kritik eşik",
  },
  {
    key: "hardware.temp_sources",
    group: "hardware",
    section: "Sıcaklık",
    type: "string",
    default: "",
    label: "İzlenecek sensörler",
    help: "Virgülle ayrılmış sensör kimlikleri (ör. coretemp/temp1). Boş bırakılırsa bulunan tüm sensörler izlenir.",
  },
  {
    key: "hardware.raid.scrub_overdue_days",
    group: "hardware",
    section: "Disk sağlığı ve RAID",
    type: "int",
    default: 35,
    min: 7,
    max: 365,
    unit: "gün",
    label: "Scrub gecikmesi uyarısı",
    help: "RAID/ZFS havuzu bu süredir doğrulanmadıysa uyarır. Sessiz veri bozulması ancak scrub ile yakalanır.",
  },
  {
    key: "hardware.report_stale_hours",
    group: "hardware",
    section: "Disk sağlığı ve RAID",
    type: "int",
    default: 6,
    min: 1,
    max: 168,
    unit: "saat",
    label: "S.M.A.R.T raporu eskime eşiği",
    help: "S.M.A.R.T ve ZFS verisi host'ta çalışan scripts/hardware.sh tarafından üretilir. Rapor bu süreden eskiyse uyarılır — sessizce eski veri göstermek, hiç göstermemekten kötüdür.",
  },

  // ---------- Kapasite tahmini (M1.5) ----------
  {
    key: "alerts.capacity_forecast_days",
    group: "alerts",
    section: "Kapasite tahmini",
    type: "int",
    default: 14,
    min: 1,
    max: 365,
    unit: "gün",
    label: "Kapasite uyarı ufku",
    help: "Bir disk bu süre içinde dolacak gibi görünüyorsa uyarır. Yarısından kısaysa kritik olur.",
  },
  {
    key: "capacity.window_days",
    group: "alerts",
    section: "Kapasite tahmini",
    type: "int",
    default: 30,
    min: 7,
    max: 365,
    unit: "gün",
    label: "Trend hesabında bakılacak geçmiş",
    help: "Uzun pencere yavaş sızıntıları yakalar, kısa pencere ani değişime hızlı tepki verir.",
  },
  {
    key: "capacity.min_history_days",
    group: "alerts",
    section: "Kapasite tahmini",
    type: "int",
    default: 5,
    min: 2,
    max: 90,
    unit: "gün",
    label: "Tahmin için gereken en az geçmiş",
    help: "Bu kadar günlük veri birikmeden tahmin yapılmaz. İki saatlik veriden 'yarın dolar' demek, bir dosya kopyalamayı felakete çevirir.",
  },
  {
    key: "capacity.min_confidence",
    group: "alerts",
    section: "Kapasite tahmini",
    type: "int",
    default: 60,
    min: 0,
    max: 100,
    unit: "%",
    label: "Alarm için gereken uyum (R²)",
    help: "Veri düz bir eğilim göstermiyorsa tahmin gösterilir ama alarm üretmez. Zıplayan seriyi doğru sanmak yanlış alarm demektir.",
  },

  // ---------- Alarm davranışı (M1.3) ----------
  {
    key: "alerts.flap_threshold",
    group: "alerts",
    section: "Bildirim davranışı",
    type: "int",
    default: 2,
    min: 1,
    max: 10,
    label: "Bildirim öncesi doğrulama turu",
    help: "Bir durum bu kadar ardışık turda aynı kalmadan bildirilmez. Sınırda gidip gelen bir değerin telefonu çaldırıp durmasını engeller.",
  },
  {
    key: "alerts.dedup_window",
    group: "alerts",
    section: "Bildirim davranışı",
    type: "int",
    default: 30,
    min: 0,
    max: 1440,
    unit: "dk",
    label: "Aynı alarmı tekrar bildirme aralığı",
    help: "Aynı sorun bu süre içinde tekrar bildirilmez. 0 = her turda bildir (önerilmez).",
  },
  {
    key: "alerts.escalate_after",
    group: "alerts",
    section: "Bildirim davranışı",
    type: "int",
    default: 60,
    min: 0,
    max: 1440,
    unit: "dk",
    label: "Çözülmeyen kritik alarmı hatırlat",
    help: "Kritik bir alarm bu süre boyunca sürerse yeniden bildirilir. 0 = kapalı.",
  },
  {
    key: "alerts.quiet_hours.enabled",
    group: "alerts",
    section: "Sessiz saatler",
    type: "bool",
    default: false,
    label: "Sessiz saatler",
    help: "Bu aralıkta bildirim gönderilmez; olaylar yine kaydedilir ve panelde görünür.",
  },
  {
    key: "alerts.quiet_hours.start",
    group: "alerts",
    section: "Sessiz saatler",
    type: "time",
    default: "23:00",
    label: "Sessiz saat başlangıcı",
  },
  {
    key: "alerts.quiet_hours.end",
    group: "alerts",
    section: "Sessiz saatler",
    type: "time",
    default: "07:00",
    label: "Sessiz saat bitişi",
  },
  {
    key: "alerts.quiet_hours.critical_bypass",
    group: "alerts",
    section: "Sessiz saatler",
    type: "bool",
    default: true,
    label: "Kritik alarmlar sessiz saatleri delsin",
    help: "Disk dolmak üzereyse ya da sunucu erişilemezse gece de haber ver.",
  },
  {
    key: "alerts.retention_months",
    group: "alerts",
    section: "Bildirim davranışı",
    type: "int",
    default: 12,
    min: 1,
    max: 120,
    unit: "ay",
    label: "Olay kaydı saklama",
  },
  {
    key: "alerts.timeline_jump_pct",
    group: "alerts",
    section: "Zaman çizelgesi",
    type: "int",
    default: 25,
    min: 5,
    max: 100,
    unit: "puan",
    label: "Sıçrama eşiği (yüzdelik metrikler)",
    help: "Zaman çizelgesinde bir dakikadan diğerine bu kadar puan artan CPU, bellek, disk ve container ölçümleri işaretlenir. Bu bir alarm değil — çizelgede 'tam o anda ne oldu' sorusunu cevaplamaya yarar.",
  },
  {
    key: "alerts.timeline_net_jump_mbps",
    group: "alerts",
    section: "Zaman çizelgesi",
    type: "int",
    default: 50,
    min: 1,
    max: 10000,
    unit: "Mbit/sn",
    label: "Sıçrama eşiği (ağ trafiği)",
    help: "Ağ hızı yüzde değil mutlak değer taşıdığı için ayrı eşik. 0'a indirilemez; kapatmak için çizelgede sıçrama filtresini kapatman yeterli.",
  },

  // ---------- Bildirim kanalları (M1.3) ----------
  // Her kanalın `min_level`'i var: aynı olay Telegram'a düşerken e-postaya
  // düşmeyebilir. Seviyeler: bilgi < uyarı < kritik.
  ...notifyChannel("telegram", "Telegram", [
    { key: "token", label: "Bot token", type: "secret" },
    {
      key: "chat_id",
      label: "Sohbet (chat) kimliği",
      type: "string",
      help: "Botun kullanıcı adı DEĞİL, sayısal kimlik (ör. 123456789). Bota bir mesaj yolladıktan sonra https://api.telegram.org/bot<TOKEN>/getUpdates adresinde result[0].message.chat.id olarak görünür.",
    },
  ]),
  ...notifyChannel("ha", "Home Assistant", [
    { key: "url", label: "Sunucu adresi", type: "string", help: "Ör. http://192.168.61.114:8123" },
    { key: "token", label: "Uzun ömürlü erişim token'ı", type: "secret" },
    {
      key: "service",
      label: "Bildirim servisi",
      type: "string",
      help: "Ör. notify.mobile_app_telefonum",
    },
  ]),
  ...notifyChannel("ntfy", "ntfy", [
    { key: "url", label: "Sunucu adresi", type: "string", help: "Varsayılan: https://ntfy.sh" },
    { key: "topic", label: "Konu (topic)", type: "string" },
    { key: "token", label: "Erişim token'ı (isteğe bağlı)", type: "secret" },
  ]),
  ...notifyChannel("discord", "Discord", [
    { key: "webhook", label: "Webhook adresi", type: "secret" },
  ]),
  ...notifyChannel("email", "E-posta", [
    { key: "smtp_host", label: "SMTP sunucusu", type: "string" },
    { key: "smtp_port", label: "SMTP portu", type: "int", default: 587 },
    {
      key: "secure",
      label: "Baştan TLS (port 465)",
      type: "bool",
      help: "587 için kapalı bırak — STARTTLS kendiliğinden kullanılır.",
    },
    { key: "user", label: "Kullanıcı adı", type: "string" },
    { key: "password", label: "Parola", type: "secret" },
    { key: "from", label: "Gönderen adresi", type: "string" },
    { key: "to", label: "Alıcı adresleri", type: "string", help: "Virgülle ayır." },
  ]),

  // ---------- Güncelleme ve yedek takibi (M1.10) ----------
  {
    key: "updates.os_alert_level",
    group: "updates",
    section: "İşletim sistemi",
    type: "enum",
    default: "security",
    label: "Ne zaman uyarılsın",
    options: [
      { value: "off", label: "Uyarma (yalnızca panelde göster)" },
      { value: "security", label: "Yalnızca güvenlik güncellemelerinde" },
      { value: "any", label: "Herhangi bir güncellemede" },
    ],
    help: "Güncellemeleri panel KURMAZ; yalnızca haber verir. Çekirdek güncellemesi yeniden başlatma ister ve bunu gece 3'te kendiliğinden yapan bir panel, çözdüğünden çok sorun çıkarır.",
  },
  {
    key: "updates.report_stale_hours",
    group: "updates",
    section: "İşletim sistemi",
    type: "int",
    default: 36,
    min: 1,
    max: 720,
    unit: "saat",
    label: "Rapor eskime eşiği",
    help: "Host'taki os-updates.sh bu süredir çalışmadıysa uyarılır — sessizce eski liste göstermek, hiç göstermemekten kötüdür.",
  },
  {
    key: "updates.image_check_cron",
    group: "updates",
    section: "Container image'ları",
    type: "cron",
    default: "40 5 * * *",
    label: "Image güncelleme kontrolü sıklığı",
    help: "Kayıt defterinden yalnızca sürüm özeti sorulur, image indirilmez.",
  },
  {
    key: "updates.image_alert",
    group: "updates",
    section: "Container image'ları",
    type: "bool",
    default: false,
    label: "Yeni image sürümünde bildirim gönder",
    help: "Varsayılan kapalı: image güncellemesi acil bir arıza değil, bir bakım işidir. Panelde her zaman görünür.",
  },
  {
    key: "backup.watch_dir",
    group: "updates",
    section: "Yedek takibi",
    type: "string",
    default: "",
    label: "İzlenecek yedek klasörü",
    help: "Host üzerindeki tam yol (ör. /mnt/yedek). Boş bırakılırsa takip kapalıdır. Yedekleme motoru M3.4'te gelecek; bu yalnızca 'en son yedek ne zaman alındı' sorusuna bakar.",
  },
  {
    key: "backup.stale_after_hours",
    group: "updates",
    section: "Yedek takibi",
    type: "int",
    default: 36,
    min: 1,
    max: 8760,
    unit: "saat",
    label: "Yedek eskime eşiği",
    help: "En yeni yedek bu süreden eskiyse alarm üretilir. Yedekleme sisteminin en sinsi arızası çökmesi değil, sessizce durmasıdır.",
  },

  /*
    ---------- Compose yığınları ----------

    Anahtarlar `appstore.*` olarak KALDI. Şablon katalogu kaldırıldı ama
    değerler veritabanında anahtara göre duruyor; yeniden adlandırmak
    kullanıcının ayarladığı yığın dizinini ve dosya sahibini sessizce
    varsayılana düşürürdü — kurulumu bir daha çalışmayacak hâle getiren,
    hiçbir uyarı vermeyen bir değişiklik olurdu.
  */
  {
    key: "appstore.stacks_dir",
    group: "files",
    section: "Compose yığınları",
    type: "dir",
    default: "/opt/stacks",
    label: "Yığın kök dizini",
    help: "Panelden kurulan her yığın bunun altında kendi klasörüne yazılır. DİKKAT: bu yol, host-helper'ın izin listesindeki compose dizin deseniyle uyuşmalı — uyuşmazsa dosya yazılır ama 'compose up' host tarafından reddedilir. Mevcut compose dizinini göstermek (ör. /home/kullanici/docker) genelde en pratik çözümdür. Panel var olan bir compose dosyasının ÜZERİNE yazmaz. Compose Yığınları ekranı bu dizini açılışta sınar ve uyuşmazlığı kurulumdan ÖNCE söyler.",
  },
  {
    key: "appstore.file_owner",
    group: "files",
    section: "Compose yığınları",
    type: "owner",
    default: "0:0",
    label: "Kurulan dosyaların sahibi",
    help: "Host'un kullanıcı ve grup listesinden seçilir (uid:gid olarak saklanır). Panel compose dosyasını root olan geçici bir container'la yazar; varsayılan 0:0 çünkü /opt gibi yollara ancak root yazabilir. Yığın dizini kendi ev dizininse (ör. /home/kullanici/docker) burayı kendi uid:gid'ine çevir — yoksa kurulan dosyalar root'a ait olur ve SSH'tan sudo'suz düzenleyemezsin.",
  },

  {
    key: "appstore.keep_backups",
    group: "files",
    section: "Compose yığınları",
    type: "int",
    default: 5,
    min: 1,
    max: 50,
    label: "Saklanacak compose yedeği",
    help: "Panel bir compose dosyasını düzenlemeden ÖNCE yanına '<dosya>.panel-yedek-<zaman>' kopyası bırakır; bu, kaç tanesinin tutulacağını belirler. Eskiler otomatik silinir. Yedekler yığın dizininde durur, panelin veri alanında değil — SSH'tan da elle geri yükleyebilirsin.",
  },

  {
    key: "docker.file_max_kb",
    group: "files",
    section: "Container dosyaları",
    type: "int",
    default: 512,
    min: 16,
    max: 20480,
    label: "Container dosya boyutu sınırı (KB)",
    help: "Container içinden okunabilecek ve içine yazılabilecek en büyük dosya. Dosya panelin belleğinden geçtiği için sınırsız bırakmak, tek bir yanlış tıklamada (ör. bir veritabanı dosyasını açmak) paneli tüketebilir. Sınırı aşan dosyalar listede görünür ama açılmaz.",
  },

  // ---------- Host zamanlanmış görevleri (M3.9) ----------
  {
    key: "hostcron.forbidden",
    group: "files",
    section: "Host cron",
    type: "string",
    default: "rm -rf /,mkfs,dd if=,shutdown,reboot",
    label: "Yasaklı komut parçaları",
    help: "Virgülle ayrılmış metinler. Bir cron komutu bunlardan birini içeriyorsa panel kaydetmez. Kötü niyeti durdurmaz (host'ta root olan zaten yazar) — kazayı durdurur. Boş bırakılırsa sınır kalkar.",
  },

  // ---------- Sunucu konsolu ----------
  {
    key: "console.forbidden",
    group: "files",
    section: "Sunucu konsolu",
    type: "string",
    default: "rm -rf /,mkfs,dd if=,:(){",
    label: "Yasaklı komut parçaları",
    help: "Virgülle ayrılmış metinler. Konsola yazılan komut bunlardan birini içeriyorsa panel host'a hiç göndermez. Host cron'daki gibi bu da kaza koruması, güvenlik sınırı değil — asıl sınır host'taki izin listesidir. Boş bırakılırsa sınır kalkar.",
  },
  {
    key: "console.history_lines",
    group: "files",
    section: "Sunucu konsolu",
    type: "int",
    default: 5000,
    min: 200,
    max: 50000,
    unit: "satır",
    label: "Konsol çıktısı üst sınırı",
    help: "Konsol penceresinde tutulacak satır sayısı. Aşıldığında en eski satırlar düşer; tarayıcının uzun bir `apt upgrade` çıktısı yüzünden yavaşlamasını engeller.",
  },

  // ---------- Veritabanı yöneticisi (M3.6) ----------
  {
    key: "dbadmin.max_rows",
    group: "files",
    section: "Veritabanı yöneticisi",
    type: "int",
    default: 500,
    min: 10,
    max: 10000,
    unit: "satır",
    label: "Sorgu satır limiti",
    help: "LIMIT'i olmayan her SELECT'e bu değer otomatik eklenir. Kazayla açılan 'SELECT * FROM olaylar' panelin belleğini yemesin diye.",
  },
  {
    key: "dbadmin.timeout_seconds",
    group: "files",
    section: "Veritabanı yöneticisi",
    type: "int",
    default: 30,
    min: 2,
    max: 600,
    unit: "sn",
    label: "Sorgu zaman aşımı",
    help: "Bağlanma ve sorgu çalıştırma için üst sınır. Süreyi aşan sorgu iptal edilir.",
  },

  // ---------- Dosya yöneticisi (M3.5) ----------
  {
    key: "files.roots",
    group: "files",
    section: "Erişim",
    type: "dirs",
    default: "/home,/mnt,/srv,/opt,/var/log",
    label: "İzinli kök dizinler",
    help: "Klasörler listeden SEÇİLİR — elle yazılan bir yol sessizce \"izinli kökler dışında\" hatası üretiyordu. Dosya yöneticisi YALNIZCA bunların altını görebilir. Boş bırakılırsa dosya yöneticisi tamamen kapanır. /proc, /sys, /dev ve /run listede olsalar bile erişilemez. /etc varsayılana DAHİL DEĞİL: okuma yükseltilmiş yetkiyle çalıştığı için sistem yapılandırmasını gözatılabilir yapmak bilinçli bir karar olmalı (shadow, sudoers ve özel anahtarlar eklense bile okunamaz).",
  },
  {
    key: "files.max_edit_kb",
    group: "files",
    section: "Erişim",
    type: "int",
    default: 512,
    min: 8,
    max: 10240,
    unit: "KB",
    label: "Düzenlenebilir dosya üst sınırı",
    help: "Bundan büyük dosyalar düzenleyicide kesilerek gösterilir; kaydetmek dosyayı kırpardı, bu yüzden salt-okunur açılır.",
  },
  {
    key: "files.max_download_mb",
    group: "files",
    section: "Erişim",
    type: "int",
    default: 100,
    min: 1,
    max: 2048,
    unit: "MB",
    label: "Yükseltilmiş indirme üst sınırı",
    help: "Panel kullanıcısının okuyamadığı (root'a ait) dosyalar geçici bir container üzerinden belleğe alınarak indirilir; bu yüzden bir tavan var. Panelin okuyabildiği dosyalar akış olarak iner ve bu sınıra takılmaz.",
  },
  {
    key: "files.scan_timeout_seconds",
    group: "files",
    section: "Disk analizi",
    type: "int",
    default: 20,
    min: 3,
    max: 300,
    unit: "sn",
    label: "Disk analizi zaman sınırı",
    help: "Klasör boyutu hesaplama bu süreyi aşarsa elde olan sonuçlar gösterilir ve 'eksik' işaretlenir. Sınırsız bir tarama büyük dosya sistemlerinde dakikalarca sürer.",
  },
  {
    key: "files.helper_image",
    group: "files",
    section: "Erişim",
    type: "string",
    default: "alpine:latest",
    label: "Yazma işlemleri için imaj",
    help: "Panel host'a doğrudan yazamaz (host kökü salt-okunur bağlı). Yazma gerektiren işlemler yalnızca hedef klasörü yazılabilir bağlayan tek seferlik bir container'da çalışır.",
  },

  // ---------- Yedekleme motoru (M3.4) ----------
  {
    key: "backup.restic_image",
    group: "updates",
    section: "Yedekleme motoru",
    type: "string",
    default: "restic/restic:latest",
    label: "restic imajı",
    help: "Yedekleme, host'a hiçbir şey kurmadan bu imajdan üretilen tek seferlik bir container içinde çalışır. Sürümü sabitlemek istersen etiketi değiştir (ör. restic/restic:0.19.1).",
  },
  {
    key: "backup.timeout_minutes",
    group: "updates",
    section: "Yedekleme motoru",
    type: "int",
    default: 120,
    min: 5,
    max: 1440,
    unit: "dk",
    label: "Yedekleme zaman aşımı",
    help: "Tek bir restic komutu bu süreyi aşarsa iş başarısız sayılır. İlk yedek en uzun sürendir; sonrakiler yalnızca değişeni yazar.",
  },

  // ---------- Merkezi log arama (M3.3) ----------
  {
    key: "logs.enabled",
    group: "logs",
    section: "Toplama",
    type: "bool",
    default: true,
    label: "Log toplama açık",
    help: "Kapatıldığında toplanmış loglar silinmez, yalnızca yenisi eklenmez.",
  },
  {
    key: "logs.sources",
    group: "logs",
    section: "Toplama",
    type: "containers",
    default: "",
    label: "Toplanacak container'lar",
    help: "Container'lar listeden işaretlenir. Hiçbiri seçilmezse çalışan tüm container'lar toplanır. Panelin kendi container'ı hiçbir zaman toplanmaz — kendi loglarını yiyerek büyürdü.",
  },
  {
    key: "logs.max_lines_per_source",
    group: "logs",
    section: "Toplama",
    type: "int",
    default: 2000,
    min: 100,
    max: 50000,
    unit: "satır",
    label: "Tur başına kaynak limiti",
    help: "Bir toplama turunda tek kaynaktan alınacak en fazla satır. Aniden konuşkanlaşan bir container'ın tüm turu tüketmesini engeller.",
  },
  {
    key: "logs.journald_enabled",
    group: "logs",
    section: "Toplama",
    type: "bool",
    default: false,
    label: "Host journald loglarını da topla",
    help: "host-helper üzerinden okunur ve izin listesinde 'journal.read' satırı gerektirir (root ekler). Satır yoksa toplama sessizce atlanır, hata vermez.",
  },
  {
    key: "logs.retention_days",
    group: "logs",
    section: "Saklama",
    type: "int",
    default: 14,
    min: 1,
    max: 365,
    unit: "gün",
    label: "Saklama süresi",
    help: "Bu süreden eski satırlar budama işinde silinir.",
  },
  {
    key: "logs.max_total_lines",
    group: "logs",
    section: "Saklama",
    type: "int",
    default: 2000000,
    min: 10000,
    max: 50000000,
    unit: "satır",
    label: "Toplam satır tavanı",
    help: "Yaş eşiği tek başına yetmez: konuşkan tek bir container saklama süresi dolmadan veritabanını gigabaytlara çıkarabilir. Tavan aşılırsa en eskiden kesilir.",
  },

  // ---------- Güvenlik (T6) ----------
  {
    key: "security.audit_retention_months",
    group: "security",
    type: "int",
    default: 24,
    min: 1,
    max: 120,
    unit: "ay",
    label: "Audit kaydı saklama",
    help: "Bu süreden eski audit kayıtları budama işiyle silinir.",
  },
  {
    key: "security.trivy_image",
    group: "security",
    section: "Açık taraması (M3.8)",
    type: "string",
    default: "aquasec/trivy:latest",
    label: "Tarayıcı imajı",
    help: "CVE taraması bu imajdan üretilen tek seferlik bir container'da çalışır. Trivy'nin açık veritabanı kalıcı bir volume'de tutulur; her tarama yeniden indirmez.",
  },
  {
    key: "security.scan_timeout_minutes",
    group: "security",
    section: "Açık taraması (M3.8)",
    type: "int",
    default: 15,
    min: 2,
    max: 120,
    unit: "dk",
    label: "Tarama zaman aşımı",
    help: "İlk tarama en uzun sürendir: açık veritabanı indiriliyor (yüzlerce MB).",
  },
  {
    key: "security.trivy_remote",
    group: "security",
    section: "Açık taraması (M3.8)",
    type: "bool",
    default: false,
    label: "İmajı kayıt defterinden oku",
    help: "Varsayılan kapalı: imaj zaten yerelde ve Docker'dan okumak hızlı. Çok katmanlı büyük imajlarda (ör. Home Assistant, 3,4 GB) Trivy Docker'dan okuyamıyor — bilinen bir sınır. Bu seçenek imajı kayıt defterinden yeniden indirir; çalışır ama uzun sürer ve bant genişliği harcar.",
  },
  {
    key: "security.scan_retention_days",
    group: "security",
    section: "Açık taraması (M3.8)",
    type: "int",
    default: 90,
    min: 7,
    max: 730,
    unit: "gün",
    label: "Tarama geçmişi saklama",
  },
  {
    key: "security.upnp_enabled",
    group: "security",
    section: "Port yönlendirme takibi (M3.8)",
    type: "bool",
    default: false,
    label: "Router'a UPnP ile port yönlendirmesi sor",
    help: "Varsayılan kapalı. Açıldığında panel yerel ağa SSDP yayını yapar ve yönlendiricideki UPnP kayıtlarını okur. YALNIZCA UPnP ile açılmış yönlendirmeler görünür — router arayüzünden elle eklenenler listede çıkmayabilir.",
  },
  {
    key: "security.upnp_timeout_seconds",
    group: "security",
    section: "Port yönlendirme takibi (M3.8)",
    type: "int",
    default: 5,
    min: 2,
    max: 30,
    unit: "sn",
    label: "UPnP zaman aşımı",
  },
  {
    key: "security.session_ttl_hours",
    group: "security",
    type: "int",
    default: 12,
    min: 1,
    max: 720,
    unit: "saat",
    label: "Oturum ömrü",
    help: "Girişte \"Beni hatırla\" işaretlenMEdiğinde geçerli olan süre. Yeni oturumlar için geçerlidir; mevcut oturumlar etkilenmez.",
  },
  {
    key: "security.remember_me_days",
    group: "security",
    type: "int",
    default: 365,
    min: 1,
    max: 3650,
    unit: "gün",
    label: "\"Beni hatırla\" süresi",
    help: "Yalnızca girişte kutu işaretlendiğinde geçerli; işaretlenmezse yukarıdaki saat değeri kullanılır. Uzun süre, cihaz kaybedildiğinde de oturumun uzun süre açık kalması demek — paylaşılan bir makinede kutuyu işaretleme.",
  },
  {
    key: "security.login_max_attempts",
    group: "security",
    type: "int",
    default: 5,
    min: 3,
    max: 20,
    label: "Hesap kilitlenmeden önceki hatalı deneme",
  },
  {
    key: "security.lockout_minutes",
    group: "security",
    type: "int",
    default: 15,
    min: 1,
    max: 1440,
    unit: "dk",
    label: "Kilitleme süresi",
  },

  // ---------- Panel işleri (T2) ----------
  {
    key: "jobs.sessions_prune_cron",
    group: "jobs",
    type: "cron",
    default: "30 * * * *",
    label: "Oturum temizliği sıklığı",
  },
  {
    key: "jobs.api_tokens_prune_cron",
    group: "jobs",
    type: "cron",
    default: "45 4 * * *",
    label: "API anahtarı budama sıklığı",
  },
  {
    key: "jobs.audit_prune_cron",
    group: "jobs",
    type: "cron",
    default: "30 4 * * *",
    label: "Audit budama sıklığı",
  },
  {
    key: "jobs.uptime_prune_cron",
    group: "jobs",
    type: "cron",
    default: "45 4 * * *",
    label: "Uptime budama sıklığı",
  },
  {
    key: "jobs.events_prune_cron",
    group: "jobs",
    type: "cron",
    default: "50 4 * * *",
    label: "Olay kaydı budama sıklığı",
  },
  {
    key: "jobs.logs_collect_cron",
    group: "jobs",
    type: "cron",
    default: "*/5 * * * *",
    label: "Log toplama sıklığı",
    help: "Sıklaştırmak gecikmeyi azaltır ama her tur container başına bir Docker çağrısı demektir. Beş dakika, aramanın işe yaraması için fazlasıyla yeterli.",
  },
  {
    key: "jobs.logs_prune_cron",
    group: "jobs",
    type: "cron",
    default: "55 4 * * *",
    label: "Log budama sıklığı",
  },
  {
    key: "jobs.vuln_scan_cron",
    group: "jobs",
    type: "cron",
    default: "0 5 * * 0",
    label: "Güvenlik açığı taraması",
    help: "Haftada bir yeter: açık veritabanı günlük güncelleniyor ama image'lar o hızda değişmiyor ve tarama uzun sürüyor.",
  },
  {
    key: "jobs.upnp_scan_cron",
    group: "jobs",
    type: "cron",
    default: "20 * * * *",
    label: "Port yönlendirme kontrolü",
    help: "Saatte bir. Amaç, senden habersiz açılan bir yönlendirmeyi erken yakalamak.",
  },
  {
    key: "jobs.port_scan_cron",
    group: "jobs",
    type: "cron",
    default: "40 * * * *",
    label: "Port haritası taraması",
    help: "Saatte bir. Bu iş kapalıysa Port Haritası ekranı ilk açılışta boş gelir ve kullanıcı elle taramak zorunda kalır.",
  },
  {
    key: "jobs.backup_scheduler_cron",
    group: "jobs",
    type: "cron",
    default: "*/10 * * * *",
    label: "Yedekleme zamanlayıcısı",
    help: "Her yedekleme işinin kendi sıklığı var; bu ayar yalnızca 'vadesi geleni kontrol et' turunun ne sıklıkta koşacağını belirler. Sık koşması ucuz — vadesi gelen iş yoksa hiçbir şey yapmaz.",
  },
  {
    key: "jobs.mqtt_publish_cron",
    group: "jobs",
    type: "cron",
    default: "*/2 * * * *",
    label: "MQTT yayını sıklığı",
    help: "Metriklerin MQTT'ye basılma sıklığı. Sıklaştırmak broker'ı yormaz (mesajlar küçük ve saklanıyor) ama HA'daki grafiklerin çözünürlüğünü artırır.",
  },

  // ---------- Dış Entegrasyon (MQTT) ----------
  {
    key: "integration.mqtt.enabled",
    group: "integration",
    section: "MQTT",
    type: "bool",
    default: false,
    label: "MQTT yayını açık",
  },
  {
    key: "integration.mqtt.host",
    group: "integration",
    section: "MQTT",
    type: "string",
    default: "",
    label: "Broker adresi",
    help: "Mosquitto container'ı aynı makinedeyse container adı da yazılabilir (ör. mosquitto).",
  },
  {
    key: "integration.mqtt.port",
    group: "integration",
    section: "MQTT",
    type: "int",
    default: 1883,
    min: 1,
    max: 65535,
    label: "Port",
  },
  {
    key: "integration.mqtt.tls",
    group: "integration",
    section: "MQTT",
    type: "bool",
    default: false,
    label: "TLS kullan",
    help: "SINIR: ev kurulumlarındaki kendinden imzalı sertifikalar için zincir doğrulaması kapalı. Yani trafik ŞİFRELENİR ama broker'ın kimliği DOĞRULANMAZ — aynı ağda araya girebilen biri broker taklidi yapabilir.",
  },
  {
    key: "integration.mqtt.username",
    group: "integration",
    section: "MQTT",
    type: "string",
    default: "",
    label: "Kullanıcı adı",
  },
  {
    key: "integration.mqtt.password",
    group: "integration",
    section: "MQTT",
    type: "secret",
    default: "",
    label: "Parola",
  },
  {
    key: "integration.mqtt.client_id",
    group: "integration",
    section: "MQTT",
    type: "string",
    default: "sunucu-paneli",
    label: "İstemci kimliği",
    help: "Broker'da aynı kimlikle iki istemci bağlanamaz; başka bir yerde de kullanıyorsan değiştir.",
  },
  {
    key: "integration.mqtt.base_topic",
    group: "integration",
    section: "MQTT",
    type: "string",
    default: "panel",
    label: "Kök konu",
    help: "Metrikler <kök>/metric/... , birleşik durum <kök>/state , olaylar <kök>/event/<kaynak> konularına basılır.",
  },
  {
    key: "integration.mqtt.timeout_seconds",
    group: "integration",
    section: "MQTT",
    type: "int",
    default: 10,
    min: 1,
    max: 120,
    unit: "sn",
    label: "Bağlantı zaman aşımı",
  },
  {
    key: "integration.mqtt.publish_events",
    group: "integration",
    section: "MQTT",
    type: "bool",
    default: true,
    label: "Olayları da yayınla",
    help: "Alarm ve olaylar oluştukları anda MQTT'ye basılır (saklanmadan). HA tarafında 'panel kritik olay ürettiğinde bildirim gönder' yazılabilir.",
  },
  {
    key: "integration.mqtt.discovery",
    group: "integration",
    section: "MQTT",
    type: "bool",
    default: false,
    label: "Home Assistant otomatik keşfi",
    help: "Açıldığında panel metrikleri HA'da kendiliğinden sensör olarak belirir; elle yapılandırma gerekmez. Kapatıldığında ilanlar geri alınır ve entity'ler HA'dan silinir.",
  },
  {
    key: "integration.mqtt.discovery_prefix",
    group: "integration",
    section: "MQTT",
    type: "string",
    default: "homeassistant",
    label: "Keşif konu öneki",
    help: "HA'nın MQTT entegrasyonundaki 'discovery prefix' ile aynı olmalı. Varsayılanı değiştirmediysen dokunma.",
  },

  // ---------- Prometheus (T12) ----------
  // 022'de otomasyonla birlikte silinmişlerdi: anahtar üretecek arayüz
  // kalmayınca /metrics kullanılamaz hâle gelmişti. Arayüz geldi, ayarlar da
  // geri geliyor.
  {
    key: "integration.prometheus.enabled",
    group: "integration",
    section: "Prometheus",
    type: "bool",
    default: false,
    label: "/metrics ucu açık",
    help: "Dış API ana şalterine BAĞLIDIR: /metrics de bearer token ile kimlik doğruluyor, o yüzden 'Dış API' kapalıyken bu ayar etkisizdir.",
  },
  {
    key: "integration.prometheus.include_containers",
    group: "integration",
    section: "Prometheus",
    type: "bool",
    default: false,
    label: "Container metriklerini de ver",
    help: "Her container için ek satır ve her scrape'te ek sorgu demek. Etikette container ADI kullanılır, id değil — id her recreate'te değişir ve Prometheus'ta her seferinde yeni bir zaman serisi açardı.",
  },

  // ---------- Dış API (T12) ----------
  {
    key: "api.enabled",
    group: "api",
    type: "bool",
    default: false,
    label: "Dış API açık",
    help: "Kapalıyken /api/v1 ve /metrics 404 döner. Bilerek kapalı geliyor: API'yi açmak, panele parola dışında ikinci bir giriş yolu açmaktır.",
  },
  {
    key: "api.rate_limit_per_minute",
    group: "api",
    type: "int",
    default: 120,
    min: 1,
    max: 10000,
    unit: "istek/dk",
    label: "Anahtar başına istek sınırı",
    help: "Meşru bir istemcinin paneli boğmasını engeller. Aşımda 429 + Retry-After.",
  },
  {
    key: "api.auth_rate_limit_per_minute",
    group: "api",
    type: "int",
    default: 10,
    min: 1,
    max: 1000,
    unit: "deneme/dk",
    label: "IP başına başarısız kimlik denemesi",
    help: "Anahtar tahmin/tarama denemesine karşı. Yalnızca BAŞARISIZ denemeler sayılır, başarılı olan sayacı sıfırlar — tek IP arkasındaki meşru trafik cezalandırılmasın.",
  },
  {
    key: "api.token_default_ttl_days",
    group: "api",
    type: "int",
    default: 90,
    min: 0,
    max: 3650,
    unit: "gün",
    label: "Yeni anahtarın varsayılan ömrü",
    help: "0 = süresiz. Anahtar üretme ekranında değiştirilebilir; bu yalnızca varsayılan.",
  },
  {
    key: "api.device_token_ttl_days",
    group: "api",
    type: "int",
    default: 30,
    min: 1,
    max: 365,
    unit: "gün",
    label: "Mobil cihaz anahtarının ömrü",
    help: "Cihaz doğrulamasından sonra otomatik üretilen anahtar için. Yenileme yeni anahtar üretip eskisini iptal eder; sızmış eski değer en fazla bu kadar yaşar.",
  },
  {
    key: "api.max_tokens_per_user",
    group: "api",
    type: "int",
    default: 20,
    min: 1,
    max: 200,
    unit: "anahtar",
    label: "Kullanıcı başına aktif anahtar",
    help: "Yalnızca iptal edilmemiş anahtarlar sayılır. İptal edilenler de sayılsaydı, anahtar döndüren bir kullanıcı bir gün kendi geçmişi yüzünden kilitlenirdi.",
  },
  {
    key: "api.max_body_bytes",
    group: "api",
    type: "int",
    default: 65536,
    min: 1024,
    max: 10485760,
    unit: "bayt",
    label: "En büyük istek gövdesi",
  },
  {
    key: "api.last_used_write_interval",
    group: "api",
    type: "int",
    default: 60,
    min: 0,
    max: 3600,
    unit: "sn",
    label: "Son kullanım yazma aralığı",
    help: "15 saniyede bir scrape eden bir Prometheus, kısma olmadan günde ~5.760 gereksiz yazma demek. IP değiştiğinde eşik beklenmez.",
  },
  {
    key: "api.idempotency_window_seconds",
    group: "api",
    type: "int",
    default: 300,
    min: 30,
    max: 3600,
    unit: "sn",
    label: "Idempotency-Key penceresi",
    help: "host-helper'ın kendi tekrar penceresiyle aynı olmalı (varsayılan 300 sn); iki farklı süre arada tanımsız bir bölge bırakır.",
  },
  {
    key: "api.token_retention_days",
    group: "api",
    type: "int",
    default: 180,
    min: 0,
    max: 3650,
    unit: "gün",
    label: "İptal edilmiş anahtar saklama süresi",
    help: "0 = hiç silme. İptal satırları audit izi için tutuluyor; bu süre onların ne kadar saklanacağını belirler.",
  },
];

const byKey = new Map(settingDefs.map((def) => [def.key, def]));

export function findSetting(key: string): SettingDef | undefined {
  return byKey.get(key);
}

export function findSettingGroup(key: string): SettingGroupDef | undefined {
  return settingGroups.find((group) => group.key === key);
}

export function defsOfGroup(groupKey: string): SettingDef[] {
  return settingDefs.filter((def) => def.group === groupKey);
}

/**
 * Bir kategorinin ayarlarını alt başlıklara böler.
 *
 * Alt başlık sırası, ayarın şemada ilk göründüğü yere göre belirlenir — ayrı
 * bir `order` alanı tutmak, er ya da geç iki ayarın aynı numarayı almasıyla
 * biterdi. Aynı ada sahip ayarlar şemada dağınık dursa bile tek blokta
 * toplanır: `alerts.temp.*` donanım bölümünün başında tanımlı olmasa da
 * "Sıcaklık" başlığı altında görünür.
 */
export function sectionsOfGroup<T extends { section?: string }>(
  defs: T[],
): { title: string | null; defs: T[] }[] {
  const sections: { title: string | null; defs: T[] }[] = [];

  for (const def of defs) {
    const title = def.section ?? null;
    const existing = sections.find((section) => section.title === title);
    if (existing) existing.defs.push(def);
    else sections.push({ title, defs: [def] });
  }

  return sections;
}
